# Generated by Django 5.2.1 on 2025-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('job_ID', models.IntegerField()),
                ('User', models.CharField(max_length=40)),
            ],
        ),
    ]
