# Generated by Django 5.2.1 on 2025-05-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='ID',
            new_name='job_ID',
        ),
    ]
