# Generated by Django 5.2.1 on 2025-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('profilePic', models.ImageField(blank=True, default='CSS/Images/default-profile-picture.png', null=True, upload_to='photos/%y/%m/%d')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('jobsTitle', models.CharField(blank=True, max_length=60, null=True)),
                ('backgroundPic', models.ImageField(blank=True, default='CSS/Images/defaultBackground.jpg', null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
