# Generated by Django 5.2.1 on 2025-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_id_appliedjobs_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
