# Generated by Django 5.2.1 on 2025-05-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appliedjobs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='id',
            new_name='Id',
        ),
    ]
