# Generated by Django 5.2.1 on 2025-05-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_id_appliedjobs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='Id',
            new_name='a7a_Id',
        ),
    ]
