# Generated by Django 5.2.1 on 2025-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default="{% static 'CSS/Images/default-profile-picture.png' %}", null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
