# Generated by Django 5.2.1 on 2025-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='backgroundPic',
            field=models.ImageField(blank=True, default="{% static 'CSS/Images/default-profile-picture.png' %}", null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
