# Generated by Django 5.2.1 on 2025-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_backgroundpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='backgroundPic',
            field=models.ImageField(blank=True, default='defaults/default-profile-picture.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='defaults/default-profile-picture.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
