# Generated by Django 5.2.1 on 2025-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_backgroundpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='backgroundPic',
            field=models.ImageField(blank=True, default='defaults/defaultBackground.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
