# Generated by Django 5.2.1 on 2025-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Admin', models.CharField(max_length=40)),
                ('CompanyName', models.CharField(max_length=40)),
                ('Title', models.CharField(max_length=40)),
                ('Salary', models.IntegerField()),
                ('Description', models.TextField()),
                ('Experience', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
