# Generated by Django 5.2.1 on 2025-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='Username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
